version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: entended_table_demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ivy
      MYSQL_PASSWORD: ivy
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "8085:8080"

volumes:
  mysql-data:
    driver: local
